name: ci

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby v${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run rspec
        run: bundle exec rspec --format documentation
