name: ci

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - 2.5
          - 2.6
          - 2.7
          - 3.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('api/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup Ruby v${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby_version: ${{ matrix.ruby-version }}

      - name: Install bundler
        run: gem install bundler -v "~> 1.17"

      - name: Execute bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run rspec
        run: bundle exec rspec --format documentation
